ami                 = "ami-0aa3620fadad9198e"       # From https://wiki.centos.org/Cloud/AWS
instance_type       = "t3a.medium"
min_size            = 3
max_size            = 5
desired_capacity    = 3
ebs_volume_size     = 16
root_volume_size    = 8
environment         = "development"
role                = "docker-swarm-manager"
instance_count      = [3]
key_name            = "docker_ssh_key"
